iiaApiBundle:
    resource: "@iiaApiBundle/Resources/config/routing.yml"
    prefix:   /
iiaApiBundle_qcm:
    resource: "@iiaApiBundle/Resources/config/routing/qcm.yml"
    prefix: /qcm
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api