security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path: /logout
                target: /
 
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
 
    providers:
        in_memory:
          memory:
            users:
                admin: { password: admin, roles: 'ROLE_ADMIN' }
 
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext