<?php

namespace iia\ApiBundle\Entity;

/**
 * GroupOfUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupOfUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
