<?php

namespace iia\ApiBundle\Entity;

/**
 * QcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QcmRepository extends \Doctrine\ORM\EntityRepository
{
}
