<?php

namespace iia\ApiBundle\Entity;

/**
 * User_qcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_qcmRepository extends \Doctrine\ORM\EntityRepository
{
}
